name: loodo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Environnement élargi pour les nouvelles versions

dependencies:
  flutter:
    sdk: flutter

  # Les versions sont mises à jour pour permettre les dernières fonctionnalités
  supabase_flutter: ^2.10.3
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Version compatible avec Dart 3.6.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
