// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFak8bVvDLjxQlj-vl73WaYPDPgQmENSQ',
    appId: '1:173016712105:web:eb96d070688fe89cf37ab8',
    messagingSenderId: '173016712105',
    projectId: 'capprojet-dbf3f',
    authDomain: 'capprojet-dbf3f.firebaseapp.com',
    storageBucket: 'capprojet-dbf3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC13ZyUSM2K36fHPsbQWNfXQwLf8pQ7opo',
    appId: '1:173016712105:android:e9353fc2593ec660f37ab8',
    messagingSenderId: '173016712105',
    projectId: 'capprojet-dbf3f',
    storageBucket: 'capprojet-dbf3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASJCMIHYAwSl_ZUywReTz98EZx0Nrq5V0',
    appId: '1:173016712105:ios:f80251a561802d8ef37ab8',
    messagingSenderId: '173016712105',
    projectId: 'capprojet-dbf3f',
    storageBucket: 'capprojet-dbf3f.firebasestorage.app',
    iosBundleId: 'com.example.capApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASJCMIHYAwSl_ZUywReTz98EZx0Nrq5V0',
    appId: '1:173016712105:ios:f80251a561802d8ef37ab8',
    messagingSenderId: '173016712105',
    projectId: 'capprojet-dbf3f',
    storageBucket: 'capprojet-dbf3f.firebasestorage.app',
    iosBundleId: 'com.example.capApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFak8bVvDLjxQlj-vl73WaYPDPgQmENSQ',
    appId: '1:173016712105:web:17f22da8c223467ff37ab8',
    messagingSenderId: '173016712105',
    projectId: 'capprojet-dbf3f',
    authDomain: 'capprojet-dbf3f.firebaseapp.com',
    storageBucket: 'capprojet-dbf3f.firebasestorage.app',
  );
}
